// packages/react/src/QRCode.jsx
import React, { useMemo } from 'react';
import { generate } from '@stone-pixel/qr-core/src/qr-core.js';
import { toStyledSVG } from '@stone-pixel/qr-core/src/qr-styled.js';

/**
 * React QR Code component with full styling customization.
 *
 * @param {object} props
 * @param {string} props.value - Text/URL to encode
 * @param {string} [props.ecLevel='M'] - Error correction: 'L', 'M', 'Q', 'H'
 * @param {number} [props.margin=4] - Quiet zone in modules
 * @param {string} [props.dotShape='square'] - Dot style: square, rounded, dots, diamond, star, heart
 * @param {string} [props.cornerSquareShape='square'] - Corner border: square, rounded, circle, extraRounded
 * @param {string} [props.cornerDotShape='square'] - Corner center: square, rounded, circle, diamond, star
 * @param {string} [props.dotColor='#000000'] - Dot color
 * @param {string} [props.cornerSquareColor] - Corner border color (defaults to dotColor)
 * @param {string} [props.cornerDotColor] - Corner center color (defaults to cornerSquareColor)
 * @param {string} [props.backgroundColor='#ffffff'] - Background color
 * @param {string} [props.gradientType] - 'linear' or 'radial'
 * @param {string[]} [props.gradientColors] - [startColor, endColor]
 * @param {number} [props.gradientRotation=0] - Gradient angle in degrees
 * @param {string} [props.centerImage] - URL or data URL for center logo
 * @param {number} [props.centerImageSize=0.25] - Logo size as fraction of QR
 * @param {number} [props.centerImageMargin=4] - Margin around logo
 * @param {string} [props.className] - CSS class
 * @param {object} [props.style] - Inline styles
 */
function QRCode({
  value,
  ecLevel = 'M',
  margin = 4,
  dotShape = 'square',
  cornerSquareShape = 'square',
  cornerDotShape = 'square',
  dotColor = '#000000',
  cornerSquareColor = null,
  cornerDotColor = null,
  backgroundColor = '#ffffff',
  gradientType = null,
  gradientColors = null,
  gradientRotation = 0,
  centerImage = null,
  centerImageSize = 0.25,
  centerImageMargin = 4,
  className = '',
  style = {},
}) {
  const svgString = useMemo(() => {
    if (!value) return '';

    try {
      const ec = centerImage ? 'H' : ecLevel;
      const qr = generate(value, { ecLevel: ec });

      return toStyledSVG(qr, {
        margin,
        dotShape,
        cornerSquareShape,
        cornerDotShape,
        dotColor,
        cornerSquareColor,
        cornerDotColor,
        backgroundColor,
        gradientType,
        gradientColors,
        gradientRotation,
        centerImage,
        centerImageSize,
        centerImageMargin,
      });
    } catch (err) {
      console.error('QR Code generation error:', err);
      return '';
    }
  }, [
    value, ecLevel, margin,
    dotShape, cornerSquareShape, cornerDotShape,
    dotColor, cornerSquareColor, cornerDotColor,
    backgroundColor,
    gradientType, gradientColors, gradientRotation,
    centerImage, centerImageSize, centerImageMargin,
  ]);

  if (!svgString) return null;

  return (
    <div
      className={className}
      style={{ display: 'inline-block', lineHeight: 0, ...style }}
      dangerouslySetInnerHTML={{ __html: svgString }}
    />
  );
}

export default QRCode;
export { QRCode };

// packages/vue/src/QRCode.vue
<template>
  <div ref="container" v-html="svgContent" class="qr-code-container"></div>
</template>

<script>
import { ref, watch, onMounted, defineComponent } from 'vue';
import { generate } from '@stone-pixel/qr-core/src/qr-core.js';
import { toStyledSVG } from '@stone-pixel/qr-core/src/qr-styled.js';

export default defineComponent({
  name: 'QRCode',

  props: {
    value: {
      type: String,
      required: true,
    },
    ecLevel: {
      type: String,
      default: 'M',
      validator: (v) => ['L', 'M', 'Q', 'H'].includes(v),
    },
    margin: {
      type: Number,
      default: 4,
    },
    dotShape: {
      type: String,
      default: 'square',
    },
    cornerSquareShape: {
      type: String,
      default: 'square',
    },
    cornerDotShape: {
      type: String,
      default: 'square',
    },
    dotColor: {
      type: String,
      default: '#000000',
    },
    cornerSquareColor: {
      type: String,
      default: null,
    },
    cornerDotColor: {
      type: String,
      default: null,
    },
    backgroundColor: {
      type: String,
      default: '#ffffff',
    },
    gradientType: {
      type: String,
      default: null,
    },
    gradientColors: {
      type: Array,
      default: null,
    },
    gradientRotation: {
      type: Number,
      default: 0,
    },
    centerImage: {
      type: String,
      default: null,
    },
    centerImageSize: {
      type: Number,
      default: 0.25,
    },
    centerImageMargin: {
      type: Number,
      default: 4,
    },
  },

  setup(props) {
    const svgContent = ref('');
    const container = ref(null);

    function renderQR() {
      if (!props.value) {
        svgContent.value = '';
        return;
      }

      try {
        const ecLevel = props.centerImage ? 'H' : props.ecLevel;
        const qr = generate(props.value, { ecLevel });

        svgContent.value = toStyledSVG(qr, {
          margin: props.margin,
          dotShape: props.dotShape,
          cornerSquareShape: props.cornerSquareShape,
          cornerDotShape: props.cornerDotShape,
          dotColor: props.dotColor,
          cornerSquareColor: props.cornerSquareColor,
          cornerDotColor: props.cornerDotColor,
          backgroundColor: props.backgroundColor,
          gradientType: props.gradientType,
          gradientColors: props.gradientColors,
          gradientRotation: props.gradientRotation,
          centerImage: props.centerImage,
          centerImageSize: props.centerImageSize,
          centerImageMargin: props.centerImageMargin,
        });
      } catch (err) {
        svgContent.value = '';
        console.error('QR Code generation error:', err);
      }
    }

    onMounted(renderQR);

    watch(
      () => [
        props.value, props.ecLevel, props.margin,
        props.dotShape, props.cornerSquareShape, props.cornerDotShape,
        props.dotColor, props.cornerSquareColor, props.cornerDotColor,
        props.backgroundColor,
        props.gradientType, props.gradientColors, props.gradientRotation,
        props.centerImage, props.centerImageSize, props.centerImageMargin,
      ],
      renderQR,
      { deep: true }
    );

    return { svgContent, container };
  },
});
</script>

<style scoped>
.qr-code-container {
  display: inline-block;
  line-height: 0;
}

.qr-code-container :deep(svg) {
  max-width: 100%;
  height: auto;
}
</style>
